# frozen_string_literal: true

source 'https://rubygems.org'

gem 'capybara'
gem 'cucumber'
gem 'mongo', '~> 2.13', '>= 2.13.1'
gem 'report_builder'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'site_prism'
